import { promises as fs } from "node:fs";
import path from "node:path";

import { z } from "zod";

import { isPageKey, pages, type PageContent, type PageKey } from "@/content/registry";

export const CONTENT_DIR = path.join(process.cwd(), "content");

export const ContentConfigSchema = z.object({
  /**
   * `original` serves the content extracted from the source site.
   * `placeholder` serves the neutral copy generated by `/templatize`, which
   * carries no text or imagery from the source. Publish with `placeholder`
   * unless you own the source material.
   */
  variant: z.enum(["original", "placeholder"]).default("original"),
});

export type ContentVariant = z.infer<typeof ContentConfigSchema>["variant"];

const CONFIG_FILE = path.join(CONTENT_DIR, "config.json");

async function readJson(file: string): Promise<unknown> {
  const raw = await fs.readFile(file, "utf8");
  try {
    return JSON.parse(raw) as unknown;
  } catch (cause) {
    throw new Error(`${path.relative(process.cwd(), file)} is not valid JSON`, {
      cause,
    });
  }
}

async function exists(file: string): Promise<boolean> {
  try {
    await fs.access(file);
    return true;
  } catch {
    return false;
  }
}

function formatIssues(error: z.ZodError): string {
  return error.issues
    .map((issue) => `  · ${issue.path.join(".") || "(root)"} — ${issue.message}`)
    .join("\n");
}

export async function readConfig(): Promise<{ variant: ContentVariant }> {
  if (!(await exists(CONFIG_FILE))) return { variant: "original" };
  return ContentConfigSchema.parse(await readJson(CONFIG_FILE));
}

export function contentFile(key: PageKey, variant: ContentVariant): string {
  const stem = variant === "placeholder" ? `${key}.placeholder` : key;
  return path.join(CONTENT_DIR, `${stem}.json`);
}

/**
 * Resolve which file backs a page. A missing `.placeholder.json` falls back to
 * the original rather than failing the build, so adding a page never requires
 * writing both variants up front.
 */
export async function resolveContentFile(
  key: PageKey,
  variant?: ContentVariant,
): Promise<{ file: string; variant: ContentVariant; fellBack: boolean }> {
  const wanted = variant ?? (await readConfig()).variant;
  const file = contentFile(key, wanted);
  if (await exists(file)) return { file, variant: wanted, fellBack: false };

  const fallback = contentFile(key, "original");
  if (wanted !== "original" && (await exists(fallback))) {
    return { file: fallback, variant: "original", fellBack: true };
  }
  return { file, variant: wanted, fellBack: false };
}

/**
 * Read, validate, and type a page's content. Throws with the offending field
 * paths so a schema/content mismatch fails the build loudly instead of
 * rendering a half-empty page.
 */
export async function loadContent<K extends PageKey>(
  key: K,
  variant?: ContentVariant,
): Promise<PageContent<K>> {
  const { file } = await resolveContentFile(key, variant);
  const relative = path.relative(process.cwd(), file);

  let raw: unknown;
  try {
    raw = await readJson(file);
  } catch (cause) {
    throw new Error(
      `Cannot read content for "${key}" from ${relative}. ` +
        `Every page in src/content/registry.ts needs a matching JSON file.`,
      { cause },
    );
  }

  const parsed = pages[key].schema.safeParse(raw);
  if (!parsed.success) {
    throw new Error(
      `${relative} does not match the "${key}" schema:\n${formatIssues(parsed.error)}`,
    );
  }
  return parsed.data as PageContent<K>;
}

/** Validate and persist a page's content. Used by the editor API only. */
export async function saveContent(
  key: PageKey,
  data: unknown,
  variant?: ContentVariant,
): Promise<void> {
  const parsed = pages[key].schema.safeParse(data);
  if (!parsed.success) {
    throw new Error(`Invalid content for "${key}":\n${formatIssues(parsed.error)}`);
  }
  const { variant: resolved } = await resolveContentFile(key, variant);
  await fs.writeFile(
    contentFile(key, resolved),
    `${JSON.stringify(parsed.data, null, 2)}\n`,
    "utf8",
  );
}

export { isPageKey, pages };
export type { PageKey };
